config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    collection do
      get 'past_list', to: 'past_list', as: 'past'
      get 'all_list', to: 'all_list', as: 'all'
    end
    post :show, on: :member
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :event, presence: true
  validates :body, presence: true
  validates :user_name, presence: true, unless: -> { user }

  def user_name
    user ? user.name : super
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]

  def create
    @new_comment = @event.comments.build(comment_params)
    @new_comment.user = current_user

    if @new_comment.save
      redirect_to @event, notice: I18n.t('controllers.comments.created')

      participants_emails(@new_comment).each do |email|
        EventMailer.comment_created(@new_comment, email).deliver_now
      end
    else
      render 'events/show', alert: I18n.t('controllers.comments.error')
    end
  end

  def destroy
    message = { notice: I18n.t('controllers.comments.destroyed')}
    if current_user_can_edit?(@comment)
      @comment.destroy!
      EventMailer.comment_destroyed(@comment).deliver_now
    else
      message = { alert: I18n.t('controllers.comments.error')}
    end
    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_comment
    @comment = @event.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_name)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
.buffer-bottom
  p = comment.body
  p
    span
      - if comment.user
        = render partial: 'users/user', object: comment.user
      - else
        em
          strong = comment.user_name

    em
      '
      = l comment.created_at, format: :long

    - if current_user_can_edit?(comment) || user_owner_of?(@event)
      '
      = link_to fa_icon('trash'), event_comment_path(comment.event, comment), method: :delete, data: { confirm: t('.destroy_confirm') }

app/views/comments/_form.html.slim
= form_for [@event, comment] do |f|
  = render partial: 'partials/errors_viewer', locals: { model: comment }

  .form-group
    = f.label :body
    = f.text_area :body, placeholder: true, class: 'form-control'

  - unless user_signed_in?
    .form-group
      = f.label :user_name
      = f.text_field :user_name, placeholder: true, class: 'form-control'

  .actions = f.submit I18n.t('comments.send'), class: 'btn btn-primary'