config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    collection do
      get 'past_list', to: 'past_list', as: 'past'
      get 'all_list', to: 'all_list', as: 'all'
    end
    post :show, on: :member
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  before_validation { email.downcase! }
  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :name, presence: true, length: { maximum: 35 }
  validates :email,
            presence: true,
            length: { maximum: 255 },
            uniqueness: true,
            format: { with: VALID_EMAIL_REGEX }

  after_commit :link_subscriptions, on: :create

  mount_uploader :avatar, AvatarUploader

  private

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: self.email).
      update_all(user_id: self.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_current_user, except: [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  private

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :name, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= form_for @user, html: { mutipart: true } do |f|
  = render partial: 'partials/errors_viewer', locals: {model: @user}

  .form-group
    = f.label :name
    = f.text_field :name, autofocus: true, class: 'form-control', placeholder: :name

  .form-group
    = f.label :email
    = f.text_field :email, autofocus: true, class: 'form-control', placeholder: :email

  .form-group
    = f.label :avatar
    p = image_tag(@user.avatar.thumb.url) if @user.avatar?
    = f.file_field :avatar, class: 'btn btn-primary'

  .actions
    = f.submit I18n.t('views.save'), class: 'btn btn-primary'
    = I18n.t('views.or')
    = link_to I18n.t('views.back'), user_path

app/views/users/_user.html.slim
span.user
  span.user-avatar
    = image_tag user_avatar(user), class: "img-icon"
  span.user-name
    = link_to " #{user.name}", user_path(user)

app/views/users/edit.html.slim
- provide(:title, I18n.t('views.settings'))

h1 = I18n.t('views.settings')

.row
  .col-md-6.buffer-top
    = render 'form'

    p.buffer-top
      = button_to I18n.t('views.change_password'), edit_user_registration_path, method: :get,class: 'btn btn-primary'

    p.buffer-top
      = button_to I18n.t('views.delete_account'), registration_path(@user), data: { confirm: I18n.t('user.destroy_confirm')}, method: :delete, class: 'btn btn-danger'

app/views/users/show.html.slim
- provide(:title, @user.name)
.text-center
  h1 = @user.name
  = image_tag user_avatar(@user)
  - if @user == current_user
    p.buffer-top
      = link_to I18n.t('views.create_event'), new_event_path, class: 'btn btn-success'

.row
  .col-md-12
    - if @user.events.any?
      h3 = I18n.t('views.organized')
      .row
        = render partial: 'events/event', collection: @user.events.asc
    - else
      p.buffer-top = I18n.t('views.organized_nothing')

/ todo события на которые вы подписаны