config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    collection do
      get 'past_list', to: 'past_list', as: 'past'
      get 'all_list', to: 'all_list', as: 'all'
    end
    post :show, on: :member
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  scope :asc, ->{
    order(datetime: :asc)
  }

  scope :past, ->{
    where('datetime < ?', Time.now).order(datetime: :desc)
  }

  scope :future, ->{
    where('datetime > ?', Time.now).order(datetime: :asc)
  }

  validates :title, presence: true, length: { maximum: 255 }
  validates :datetime, presence: true
  validates :address, presence: true, length: { maximum: 255 }
  validates :user, presence: true
  validates :pincode, length: 4..10, format: { with: /\A\d+\z/ }, allow_blank: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(input_pincode)
    pincode == input_pincode
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index, :all_list, :past_list]
  before_action :set_event, only: [:show]
  before_action :set_current_user_event, only: [:edit, :update, :destroy]
  before_action :pincode_guard!, only: [:show]
  def index
    @events = Event.paginate(:page => params[:page], :per_page => 12).future
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @subscription = current_user.subscriptions.find_by(event_id: @event.id) if current_user
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    user = @event.user
    @event.destroy
    redirect_to user_path(user), notice: I18n.t('controllers.events.destroyed')
  end

  def past_list
    @events = Event.paginate(:page => params[:page], :per_page => 12).past
    render :index
  end

  def all_list
    @events = Event.paginate(:page => params[:page], :per_page => 12).asc
    render :index
  end

  private

  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :datetime, :address, :description, :pincode)
  end

  def pincode_guard!
    return true if @event.pincode.blank?
    return true if @event.user == current_user

    if current_user
      if params[:pincode] && @event.pincode_valid?(params[:pincode])
        cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
      end

      unless @event.pincode_valid?(cookies.permanent["events_#{@event.id}_pincode"])
        flash.now[:alert] = t('controllers.events.pin_alert') if params[:pincode]
        render 'pincode_form'
      end
    else
      redirect_to new_user_session_path, notice: t('controllers.events.redirect')
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.slim
.col-sm-6.col-md-4
  .thumbnail
    = content_tag 'div', '', class: 'event-background', style: "background-image: url(#{event_thumb(event)})"
    .thumbnail-inner.event-info-inner
      .caption
        .event-description
          h3 = link_to event.title, event_path(event)
          h3
            small = l event.datetime, format: :long
          buffer-both = event.address

        - event.visitors.first(6).each do |user|
          = image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name
        - if event.visitors.count > 6
          ' ...

app/views/events/_event_large.html.slim
.event-info.row
  .col-md-12
    = content_tag 'div', '', class: 'event-background', style: "background-image: url(#{event_photo(@event)})"
    .event-info-inner.row
      .col-md-6
        .event-description
          h1 = @event.title
          h3 = l @event.datetime, format: :long
          h3
            small = @event.address
          p = @event.description

          - if current_user_can_edit?(@event)
            .buffer-top
              = link_to I18n.t('views.events.change'), edit_event_path(@event), class: 'btn btn-primary'
              = ' '
              = link_to I18n.t('views.events.delete'), @event, method: :delete, data: { confirm: I18n.t('views.events.destroy_confirm')}, class: 'btn btn-danger'

app/views/events/_form.html.slim
= form_for @event do |f|
  = render partial: 'partials/errors_viewer', locals: { model: @event }

  .form-group
    = f.label :title
    = f.text_field :title, autofocus: true, class: 'form-control', placeholder: true

  .form-group
    = f.label :address
    = f.text_field :address, autofocus: true, class: 'form-control', placeholder: true

  .form-group
    = f.label :datetime
    p = f.datetime_select :datetime, autofocus: true, class: 'form-control'

  .form-group
    = f.label :description
    = f.text_field :description, autofocus: true, class: 'form-control', placeholder: true

  .form-group
    = f.label :pincode
    = f.text_field :pincode, autofocus: true, class: 'form-control', placeholder: true


  .actions
    = f.submit I18n.t('views.save'), class: 'btn btn-primary'
    = I18n.t('views.or')
    = link_to I18n.t('views.back'), :back

app/views/events/edit.html.slim
- provide(:title, I18n.t('views.events.edit'))

h1 = I18n.t('views.events.edit')
= render 'form'

app/views/events/index.html.slim
- provide(:title, I18n.t('views.events.events'))

h1 = I18n.t('views.events.events')

.buffer-both
  = link_to I18n.t('views.create_event'), new_event_path, class: 'btn btn-success'

.buffer-both
  = link_to 'Прошедшие события', past_events_path, method: :get, class: 'btn btn-primary'
  '
  = link_to 'Все', all_events_path, method: :get, class: 'btn btn-primary'
  '
  = link_to 'Будущие события', root_path, class: 'btn btn-primary'

  p = will_paginate

.row.buffer-bottom
  = render partial: 'events/event', collection: @events

.buffer-both
  = will_paginate

app/views/events/new.html.slim
- provide(:title, I18n.t('views.create_event'))

h1 = I18n.t('views.create_event')

.row
  .col-md-6.buffer-top
    = render 'form'

app/views/events/pincode_form.html.slim
- provide(:title, t('views.events.acces'))

.row
  .col-md-6.col-md-offset-3
    .panel.panel-default.devise-bs
      .panel-heading
        h2 = t('views.events.acces')

      .panel-body
        = form_tag('', method: :post) do |f|

          .form-group
            = label :pincode, t('activerecord.attributes.event.pincode')
            = text_field_tag :pincode, params[:pincode], class: 'form-control', placeholder: t('activerecord.attributes.event.pincode'), type: "password"

          .actions
            = submit_tag t('views.send'), class: 'btn btn-primary'
            '
            = t('views.or')
            '
            = link_to t('views.back'), :back

app/views/events/show.html.slim
- provide(:title, I18n.t('activerecord.models.event'))

.event
  = render partial: 'events/event_large', object: @event

  .row
    .col-md-8
      = content_tag 'div', '', id: 'map', data: { address: @event.address }, class: 'event-map'

      .event-photos
        .event-photos-gallery
          = render partial: 'photos/photo', collection: @event.photos.except(@new_photo)

        - if user_subscribed?(@event) || user_owner_of?(@event)
          .event-photo-form
            = render partial: 'photos/form', locals: { photo: @new_photo || @event.photos.build }

      .event-comments.buffer-top
        = render partial: 'comments/form', locals: { comment: @new_comment || @event.comments.build }
        .buffer-both
          = render partial: 'comments/comment', collection: @event.comments.except(@new_comment)

    .col-md-4
      .event-owner
        h4 = I18n.t('subscriptions.subscription.creator')
        p = render partial: 'users/user', object: @event.user

      .event-subscriptions
        h4 = I18n.t('subscriptions.subscription.followers')
        p = render partial: 'subscriptions/subscription', collection: @event.subscriptions.except(@new_subscription)

      .event-subsription-form
        p = render partial: 'subscriptions/form', locals: { subscription: @new_subscription || @event.subscriptions.build }