config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    collection do
      get 'past_list', to: 'past_list', as: 'past'
      get 'all_list', to: 'all_list', as: 'all'
    end
    post :show, on: :member
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  belongs_to :event
  belongs_to :user, optional: true

  validates :event, presence: true
  validates :user_name, presence: true, unless: -> { user }
  validates :user_email,
            presence: true,
            format: VALID_EMAIL_REGEX,
            uniqueness: { scope: :event_id },
            unless: -> { user }

  validates :user, uniqueness: { scope: :event_id }, if: -> { user }

  def user_name
    user ? user.name : super
  end

  def user_email
    user ? user.email : super
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_subscription, only: [:destroy]
  before_action :check_email_duplication, only: [:create]

  def create
    @new_subscription = @event.subscriptions.build(subscription_params)
    @new_subscription.user = current_user

    if current_user == @event.user
      redirect_to @event, alert: I18n.t('controllers.subscription.alert_for_owner')
    elsif @new_subscription.save
      redirect_to @event, notice: I18n.t('controllers.subscription.created')
      EventMailer.subscription_created(@new_subscription).deliver_now
    else
      render 'events/show', alert: I18n.t('controllers.subscription.error')
    end
  end

  def destroy
    message = { notice: I18n.t('controllers.subscription.destroyed') }

    if current_user_can_edit?(@subscription)
      @subscription.destroy!
      EventMailer.subscription_destroyed(@subscription).deliver_now
    else
      message = { alert: I18n.t('controllers.subscription.error') }
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_subscription
    @subscription = @event.subscriptions.find(params[:id])
  end

  def subscription_params
    params.fetch(:subscription, {}).permit(:user_name, :user_email)
  end

  def check_email_duplication
    return if current_user
    if User.find_by(email: subscription_params[:user_email])
      redirect_to @event, alert: I18n.t('controllers.subscription.email_duplication')
    end
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.slim
= form_for [@event, subscription] do |f|
  = render partial: 'partials/errors_viewer', locals: { model: subscription }

  - unless user_signed_in?
    .form-group
      = f.label :user_name
      = f.text_field :user_name, placeholder: true, class: 'form-control'

    .form-group
      = f.label :user_email
      = f.text_field :user_email, placeholder: true, class: 'form-control'

  - unless user_owner_of?(@event) || user_subscribed?(@event)
    .actions = f.submit I18n.t('subscriptions.subscription.subscribe'), class: 'btn btn-primary'

  - if user_subscribed?(@event)
    = link_to "Отписаться", event_subscription_path(@event, @event.subscriptions.find_by(user_id: current_user.id)), method: :delete, data: { confirm: t('subscriptions.subscription.destroy_confirm') }, class: 'btn btn-primary'

app/views/subscriptions/_subscription.html.slim
span.subscription
  - if subscription.user
    = render partial: 'users/user', object: subscription.user
  - else
    em = subscription.user_name

  - if current_user_can_edit?(subscription)
    '
    = link_to fa_icon('times'), event_subscription_path(subscription.event, subscription), method: :delete, data: { confirm: t('.destroy_confirm') }

  '  |